NDiary/Controllers/AdminPagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NDiary.Data;
using NDiary.ViewModels;
using NDiary.Model;

namespace NDiary.Controllers
{
    public class AdminPagesController : Controller
	{
		private Database _database;
		List<User> users;
		List<Role> roles;
		public AdminPagesController(Database database)
		{
			_database = database;
		}

		//public IActionResult ListUsers()
		//{
		//	List<UserRole> roleModels = roles.Select(r => new UserRole(r.Id, r.Name)).ToList();
		//	UserListViewModel viewModel = new() {Roles = roleModels, Users = users };
		//	//var users = _database.Users.Include(r => r.Role).Include(s => s.Student);
		//	//return View(users.ToList());
		//	return View(viewModel);
		//}
		public IActionResult ListGroups()
		{

			var groups = _database.Groups.Include(f => f.Faculty);
			return View(groups.ToList());
		}
	}
}

NDiary/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using NDiary.Model;
using NDiary.Data;

namespace NDiary.Controllers
{
    public class HomeController : Controller
    {
		private Database _database;
		public HomeController(Database database)
		{
			_database = database;
			_database.Users.Load();
			_database.Students.Load();
			
		}
		[Authorize(Roles = "admin")]
        public IActionResult Index()
        {
			//string role = User.FindFirst(x => x.Type == ClaimsIdentity.DefaultRoleClaimType).Value;
			return View();
		}
		[Authorize(Roles = "admin")]
		public IActionResult Admin()
		{
			return View();
		}
		[Authorize(Roles = "student")]
        public IActionResult Student()
        {
			string login = User.Identity.Name;
			User user = _database.Users.First(q => q.Login == login) as User;
			//ViewBag.name = user.Student.Name;
			//ViewBag.val = user.Student.Group.Name;
			//List<Student> students = _database.Students.Where(q => q.Group == user.Student.Group).ToList();
			return View();
		}
		[Authorize(Roles = "parent")]
		public IActionResult Parent()
		{
			return View();
		}
		[Authorize(Roles = "teacher")]
		public IActionResult Teacher()
		{
			return View();
		}
	}
}

NDiary/Controllers/StudentPagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NDiary.Data;
using NDiary.Model;

namespace NDiary.Controllers
{
    public class StudentPagesController : Controller
	{
		private Database _database;
		public StudentPagesController(Database database)
		{
			_database = database;
		}
		
		public IActionResult ProfilePage()
		{
			int id = Convert.ToInt32(User.Claims.FirstOrDefault(q => q.Type == "UserId").Value);
			var student = _database.Students.Where(g => g.UserId == id).First();
			var group = _database.Groups.Where(g => g.Id == student.GroupId).First();
			var faculty = _database.Faculties.Where(g => g.Id == group.FacultyId).First();
			group.Faculty = faculty;
			student.Group = group;
			return View(student);
		}
		public IActionResult GroupPage()
		{
			int id = Convert.ToInt32(User.Claims.FirstOrDefault(q => q.Type == "UserId").Value);
			var student = _database.Students.Where(g => g.UserId == id).First();
			List<Student> students = _database.Students.Where(q => q.GroupId == student.GroupId).ToList();

			return View(students);
		}
		public IActionResult DiaryPage()
		{
			int id = Convert.ToInt32(User.Claims.FirstOrDefault(q => q.Type == "UserId").Value);
			var student = _database.Students.Where(g => g.UserId == id).First();

			return View();
		}
	}
}

NDiary/Views/Home/Admin.cshtml
<h1>Admin</h1>
<a asp-controller="Account" asp-action="Register">Добавить в систему</a>

<a asp-controller="AdminPages" asp-action="ListUsers">Пользовтели</a>
<a asp-controller="AdminPages" asp-action="ListGroups">Группы</a>
<a asp-controller="StudentPages" asp-action="SchedulePage">Расписание</a>
@*  <a asp-action="Student" asp-controller="Home">sfsd</a> *@

NDiary/Views/Home/Parent.cshtml
<p>
	parent
</p>

NDiary/Views/Home/Student.cshtml
@model Student

<a>student</a>
@* <div class="conteiner">
	<ul>
		<li><a href="#">Дневник</a></li>
		<li>
			<a asp-controller ="StudentPages" asp-action="ProfilePage" asp-route-name="@ViewBag.name"
							asp-route-val="@ViewBag.val">Профиль</a>
		</li>
		<li><a asp-controller="StudentPages" asp-action="GroupPage">Моя группа</a></li>
		@* asp-route-val="@ViewBag.val
		<li><a href="#">Портфолио</a></li>
		<li><a href="#">Приказы</a></li>
	</ul>
</div>
<h1>Личный кабинет</h1> *@
@* <p>
	@Model.Name <br/>
	@Model.Surname <br />
	@Model.Phone <br />
	@Model.Email <br />

</p> *@

<li>
	<ul><a asp-controller="StudentPages" asp-action="DiaryPage">Дневник</a></ul>
	<ul><a asp-controller="StudentPages" asp-action="ProfilePage">Профиль</a></ul>
	<ul><a asp-controller="StudentPages" asp-action="GroupPage">Группа</a></ul>
</li>

NDiary/Views/Home/Teacher.cshtml
<p>
	teacger

</p>